name: ars_carla

dependencies:
  - python=3.7
  - pip=19.2.3
  - pip:
    - opencv-python==4.5.1.48
    - tensorflow==2.4.1
    - ray==1.11
    - protobuf==3.20.0
    - carla==0.9.13
    - notebook==6.5.5
    - matplotlib==3.3.4